### ISSUE TITLE
GTK3: proposal for fixing button size in calculator widget

### ISSUE THREAD

**Issue by hansu** [LinuxCNC/linuxcnc#1436]
As my little hack for increasing the Ok and Cancel button for the calculator widget (https://github.com/LinuxCNC/linuxcnc/pull/1029) does not work any longer with Gtk3, here some possibilities for the new layout. What would you prefer?

We can have it close to the Gtk2 version (1):

<img src="https://user-images.githubusercontent.com/67957916/145474155-a1fca9bb-1ac6-40b5-b1d3-cceaea68ff0c.png" width="500">

or integrated (2):
<img src="https://user-images.githubusercontent.com/67957916/145477380-2629bc73-853c-45fb-a766-a09718c832a2.png" width="500">

or (I played a little bit around) a slighty bigger Ok button (3):
<img src="https://user-images.githubusercontent.com/67957916/145477450-f8d1a080-8994-46bc-a62a-d5c02e0a9331.png" width="500">

or (4):
<img src="https://user-images.githubusercontent.com/67957916/145477454-9a52d6db-419e-4e48-a802-d7a2db4af7e9.png" width="500">

or (5):
<img src="https://user-images.githubusercontent.com/67957916/145477456-10676ac5-5d63-4ea0-8afa-1d5cba2bfbec.png" width="500">

**Comment by rene-dev** [comment]
I prefer 2

**Comment by jethornton** [comment]
I agree, 2 looks the best to me.

JT

**Comment by andypugh** [comment]
On Thu, 9 Dec 2021 at 21:45, jethornton ***@***.***> wrote:

> I agree, 2 looks the best to me.


I don't _like_ 5, but feel that it might be the most practical.

-- 
atp

**Comment by hansu** [comment]
Some more inspiration... :stuck_out_tongue_winking_eye:
Feel free if you have some better ideas....

<img src="https://user-images.githubusercontent.com/67957916/145619752-ec636d9e-31f5-4ab9-a6b2-b4e4adc4e508.png" width="500">

<img src="https://user-images.githubusercontent.com/67957916/145620108-e4cdf2af-4e3a-48cc-9241-2e3b7455e56f.png" width="500">

**Comment by LJspice** [comment]
![image](https://user-images.githubusercontent.com/8888722/145660829-f9a5e575-cc5c-4cf6-8c2f-bd2a81649cf1.png)

Apologies for the MS paint mockup...

**Comment by hansu** [comment]
<img src="https://user-images.githubusercontent.com/67957916/145707908-090e11cd-7580-46e4-93b5-6dff6e6d9e5e.png" width="500">

**Comment by gibsonc** [comment]
Question:
While updating these widgets, should we try remediate the deprecation warnings while we are at it as part of the GTK3 effort?
For example
GtkTable -> GtkGrid
VBox / HBox -> Box with orientation
reparent()
modify_font() 
etc.

**Comment by hansu** [comment]
Yeah we can do that (except GtkTable -> GtkGrid as the glade editor is not supporting Gtk.Grid right now afaik). But where do you get deprecation warnings?

**Comment by hansu** [comment]
What do you think of a reduced variant of the calculatorwigdet that only shows numbers?
IMHO it is not optimal to have that many calculation buttons if only a tool number has to be entered.
So I would suggest to add a bool parameter like `showReduced` to the Calculator function.

Also a thought: We can create the buttons in the code without the glade file. That allows a custom placement of the buttons depending on the use case and we could use layouts that are not supported by the Glade-editor (grid for example).

**Comment by gibsonc** [comment]
So I have been basing all my experimental changes on Mint 20 which is based on Debian 11 (Bullseye.) That ships with Glade 3.22 and I target Gtk 3.20 which will then start to highlight all the deprecations. I guess the wider question is what the entry OS level requirement will be for the next major release. At some point, just like with Python2 there has to be a clean break to bring everything up as up to date and clean up as much as possible or one will never move forward.

As for your code question, I guess it depends. I was drawn to Glade at first because the barrier to entry was lower for creating an interface (this is my first experience with Gtk.) That said, I soon found it easier to just redo the entire calculator from scratch than try update the Gtk2 version of the XML file. I could just as well have spent the time and learned to do it directly in code instead.

![gtk2](https://user-images.githubusercontent.com/10432711/147565305-544bdf57-59f0-4503-8f5e-81595a5b9e3f.png)
![gtk2_1](https://user-images.githubusercontent.com/10432711/147565308-63c7020a-ed2e-40ad-82c2-673549813aed.png)

**Comment by hansu** [comment]
Ahh yes, I also have Glade 3.22 on my system. I don't know why, but I always used Glade 3.8.6. Maybe because that's the latest version for GTK2 :smile: 

So then I would also like to get rid of the deprecated items. Any objections?
