### ISSUE TITLE
Package menu entry errors

### ISSUE THREAD

**Issue by phillc54** [LinuxCNC/linuxcnc#1930]
Menu in package installation of 2.9 from the buildbot:
Missing menu entries for PnCconf and StepConf.
Latency Test appears under Documentation.

**Comment by SebKuzminsky** [comment]
This is partially fixed in master now.  As of 68680aa8 i see the following behavior:

# With just `linuxcnc-uspace` installed
Everything shows up in `Accessories`, but should not:
![Screenshot from 2022-08-17 14-38-35](https://user-images.githubusercontent.com/400548/185239031-bbd3987b-2f36-4d10-b143-803266263d94.png)

Everything shows up in `CNC` too, which is good, but this should be the only place.  And `latency-test` is in `CNC/Documentation`, should be in `CNC`:
![Screenshot from 2022-08-17 14-36-47](https://user-images.githubusercontent.com/400548/185239035-f9ef85e2-898f-49ce-ba92-021e03e282c3.png)

# With all the docs installed
Again everything is in `Accessories`, where it doesn't belong.
![Screenshot from 2022-08-17 14-44-33](https://user-images.githubusercontent.com/400548/185239986-e975f39f-30e4-4642-be78-edbf49d33d57.png)

The docs all show up in `CNC`, but some are in `CNC/Documentation` and some in `CNC/G-Code Quick-Reference`
![Screenshot from 2022-08-17 14-44-12](https://user-images.githubusercontent.com/400548/185239988-9932d288-ec18-4f3d-99dd-b7ae2bbcbb46.png)
![Screenshot from 2022-08-17 14-43-55](https://user-images.githubusercontent.com/400548/185239990-64c46dcc-348f-4def-a43b-18fa970bfb1e.png)

**Comment by phillc54** [comment]
Similar in Buster with 6c25f7eec, there is a slight difference with G-Code Quick Reference
<img width="591" alt="Screen Shot 2022-08-18 at 4 52 49 pm" src="https://user-images.githubusercontent.com/2746571/185326740-baeb7ebc-f5b4-4b47-8198-691c7e39b592.png">
<img width="384" alt="Screen Shot 2022-08-18 at 4 53 30 pm" src="https://user-images.githubusercontent.com/2746571/185326855-79bc16af-88bc-4a1f-b181-d7102f9289d9.png">

**Comment by petterreinholdtsen** [comment]
Where a menu entry show up in the menu structure is controlled using the
Categories values in the .desktop file.

Perhaps these values need a cleanup?

-- 
Happy hacking
Petter Reinholdtsen
