### ISSUE TITLE
Unicode characters from man pages not correctly converted to HTML

### ISSUE THREAD

**Issue by hansu** [LinuxCNC/linuxcnc#2140]
Man pages like this
![grafik](https://user-images.githubusercontent.com/67957916/201494657-68aa5141-9f60-4700-b23d-bc8d90a31d3b.png)

Are converted to HTML like this (http://linuxcnc.org/docs/2.9/html/man/man9/toggle.9.html):

<h2>NAME
<a name="NAME"></a>
</h2>

<p style="margin-left:11%; margin-top: 1em">toggle -
’push-on, push-off’ from momentary
pushbuttons</p>

<h2>SYNOPSIS
<a name="SYNOPSIS"></a>
</h2>

loadrt toggle [count=N\|names=name1[,name2...]] 

<h2>DESCRIPTION
<a name="DESCRIPTION"></a>
</h2>

<p style="margin-left:11%; margin-top: 1em">â
ââââ ââââ
<br>
in : âââââââ
ââââââââââ
âââ <br>
â
âââââââââââââ
<br>
out: âââââââ
ââââââ</p>

**Comment by petterreinholdtsen** [comment]
[Hans Unzner]
> Are converted to HTML like this
> (http://linuxcnc.org/docs/2.9/html/man/man9/toggle.9.html):

This rule in docs/src/Submakefile seem to be doing the conversion:

$(DOC_DIR)/html/man/%.html: $(DOC_DIR)/man/%
        @echo Formatting $(notdir $<) as HTML
        @mkdir -p $(dir $@)
#   Attention! This is a temporary fix until Groff 1.23 is released. Should be
#   set back to "-m man" when 1.23 is available.
#       This fixes the formatting of subsections and appearance in the toc.
#   It uses the local an-old.tmac instead of the one which is shipped with Groff.
        @(cd $(DOC_DIR)/man; groff -Thtml -m an-old-fixed -M . stylesheet.9 $(patsubst $(DOC_DIR)/man/%,%,$<)) > $@

My Bullseye machine uses groff version 1.22.4-6.  If we instead use
pandoc to convert (pandoc -t html), we get UTF-8 characters in the HTML
document, but sadly the space character used are not displayed properly,
so the end result is unreadable too.  Perhaps we can tell pandoc somehow
to preserve the whitespace in that block?

<URL: https://stackoverflow.com/questions/52732988/nroff-groff-does-not-properly-convert-utf-8-encoded-file >
claim groff do not really understand UTF-8, which is my experience too.
Luckily the 'man' command handle UTF-8 correctly.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
I managed to find a solution this issue during this weekends developer
gathering using preconv.

-- 
Happy hacking
Petter Reinholdtsen
