### ISSUE TITLE
Gmoccapy: Window width too big because of too many displayed h-buttons

### ISSUE THREAD

**Issue by hansu** [LinuxCNC/linuxcnc#2387]
This affects the configurations "8-axis" and "9-axis":

![grafik](https://user-images.githubusercontent.com/67957916/223843375-b34c63d6-4910-4021-9656-8a498d052ff7.png)

After clicking one of the arrow-buttons, the number of displayed buttons is reduced and the window width can the decreased manually:

![grafik](https://user-images.githubusercontent.com/67957916/223844912-7e716c23-c9ac-458a-ac94-5f02799718b5.png)

Brought to light by @SebKuzminsky's [config-test](https://github.com/SebKuzminsky/linuxcnc-config-test) if someone doesn't know that yet.

**Comment by gmoccapy** [comment]
solved and fixed

**Comment by hansu** [comment]
I noticed that also the minimal height is 836 pixels with 9 axes. This is because of the jog buttons:
![grafik](https://github.com/LinuxCNC/linuxcnc/assets/67957916/24217e84-730a-4574-b792-05844dddbb35)

Maybe we should show those buttons in this case in 5 columns and decrease the size. So something like this:

![grafik](https://github.com/LinuxCNC/linuxcnc/assets/67957916/98dcb51f-6daf-4b7b-af0d-059f6e8f0ebd)

**Comment by gmoccapy** [comment]
That might be a solution, but would require a complete rework of the place jog buttons part. I do think that actually Noone is using a 9 axis machine with linuxcnc, it is just the ability to show that it would be possible.

I prefer, that we both takes the little time we have to vćlear up the code, get rid of warnings and invest more time in CSS Styling etc. I would like rundet Buttons with shapes and aluminum background and an custom CSS file etc. Al the styling to be applied automatically to embedded tabs, as otherwise the user uses a dark interface with clearlooks embedded tabs, or he has to use a python file to load the embedded tabs just to set the design, etc...
