### ISSUE TITLE
reference to nonexistent files in CONTRIBUTING

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#435]
docs/SubmittingPatches and docs/developer-certificate-of-origin are referenced in https://github.com/LinuxCNC/linuxcnc/blob/master/CONTRIBUTING.md
but they dont exist.

**Comment by rene-dev** [comment]
style guide should be linked somwehere: http://linuxcnc.org/docs/2.7/html/code/style-guide.html

**Comment by rene-dev** [comment]
contributing seems to be here: http://linuxcnc.org/docs/2.7/html/code/contributing-to-linuxcnc.html

**Comment by jepler** [comment]
I'm closing this issue because the item mentioned in the issue's title is resolved by 7a1bfbcfcf9d31d92e52d1dc8674840f54ea54b4 -- this does not mean that the other issues mentioned in the comments are unimportant, but as an issue has only one open/closed state I prefer to close this one.  Please create further issues or pull requests for these other problems you have identified.
